copyright = "© Criticmind 2024 - 2025 · All rights reserved."
defaultContentLanguage = "en"
disableKinds = ["taxonomy"]
enableRobotsTXT = true
languageCode = "en"
timeZone = "America/New_York"
timeout = "120s"
title = "Criticmind Games Gallery"

[params]
  defaultTheme = "dark"
  description = "A gallery of games screenshots and artwork."
  title = "Games Gallery"
  # [params.author]
  #   email = "user@example.com"
  #   name = "Your Name"
  # [params.socialIcons]
    # facebook = "https://www.facebook.com/"
    # instagram = "https://www.instagram.com/"
    # github = "https://github.com/criticmind/"
    # youtube = "https://www.youtube.com/"
    # email = "mailto:user@example.com"
    #website = "https://example.com"
    #mastodon = "https://example.com"
    #pixelfed = "https://example.com"
    #mixcloud = "https://example.com"
    #flickr = "https://www.flickr.com"
    #500px = "https://500px"
    #whatsapp = "1234567890"
  [params.gallery]
    #boxSpacing = 10
    #targetRowHeight = 288
    #targetRowHeightTolerance = 0.25

[outputs]
  home = ["HTML", "RSS"]
  page = ["HTML"]
  section = ["HTML"]

[imaging]
  quality = 75
  resampleFilter = "CatmullRom"
  [imaging.exif]
    disableDate = false
    disableLatLong = true
    includeFields = "ImageDescription|Orientation"

[module]
  [module.hugoVersion]
    min = "0.121.2"
  [[module.imports]]
    path = "github.com/nicokaiser/hugo-theme-gallery/v4"

# [menu]
#   [[menu.footer]]
#     name = "GitHub"
#     url = "https://github.com/nicokaiser/hugo-theme-gallery/"
#     weight = 3

[services]
  [services.rss]
    limit = 100
